# Generated by Django 3.0.7 on 2020-09-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
