# Generated by Django 3.0.7 on 2020-09-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobApp', '0002_auto_20200908_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='image',
            field=models.ImageField(default='download.png', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='image',
            field=models.ImageField(default='download.png', null=True, upload_to=''),
        ),
    ]
